sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t niallquigley/docker-react .

script:
  - docker run -e CI=true niallquigley/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-use-west-2-24232353454"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
